name: WordPress Plugin 測試

env:
    PLUGIN_NAME: "power-webinar"
    REPO_URL: "https://github.com/j7-dev/wp-power-webinar.git"
    PHP_VERSION: "8.1"
    WP_DB_NAME: test
    WP_DB_USER: root
    WP_DB_PASS: root
    WP_DB_PORT: 10083

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: ${{ env.WP_DB_PASS }}
                    MYSQL_DATABASE: ${{ env.WP_DB_NAME }}
                ports:
                    - ${{env.WP_DB_PORT}}:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: 檢出程式碼
              uses: actions/checkout@v4

            - name: 設定 PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PHP_VERSION }}
                  extensions: mysqli, mbstring, xml, zip, gd, curl
                  tools: composer, wp-cli

            - name: 等待 MySQL 準備就緒
              run: |
                  until mysqladmin ping -h 127.0.0.1 -P ${{env.WP_DB_PORT}} --silent; do
                    echo '等待 MySQL 啟動...'
                    sleep 2
                  done

            - name: 下載並設定 WordPress
              run: |
                  # 下載 WordPress 到上層目錄
                  wp core download --path=/tmp/wordpress
                  
                  # 建立 wp-config.php
                  cd /tmp/wordpress
                  wp config create \
                    --dbname=${{ env.WP_DB_NAME }} \
                    --dbuser=${{ env.WP_DB_USER }} \
                    --dbpass=${{ env.WP_DB_PASS }} \
                    --dbhost=127.0.0.1 \
                    --dbprefix=wp_ \
                    --extra-php <<PHP
                  define( 'WP_DEBUG', true );
                  define( 'WP_DEBUG_LOG', true );
                  define( 'WP_DEBUG_DISPLAY', false );
                  PHP

            - name: 初始化 WordPress
              run: |
                  cd /tmp/wordpress
                  # 使用 WP-CLI 安裝 WordPress
                  wp core install \
                    --url=http://localhost \
                    --title="Test Site" \
                    --admin_user=admin \
                    --admin_password=admin \
                    --admin_email=admin@test.com \
                    --skip-email

            - name: 安裝外掛
              run: |
                  cd /tmp/wordpress/wp-content/plugins
                  
                  # 複製檢出的外掛程式碼到 WordPress plugins 目錄
                  cp -r $GITHUB_WORKSPACE ./${{ env.PLUGIN_NAME }}
                  
                  # 或者從其他 repo 克隆
                  # git clone ${{ env.REPO_URL }} ${{ env.PLUGIN_NAME }}

            - name: 安裝依賴 composer install
              run: |
                  cd /tmp/wordpress/wp-content/plugins/${{ env.PLUGIN_NAME }}
                  
                  # 安裝 Composer 依賴（如果存在）
                  if [ -f "composer.json" ]; then
                    composer install --prefer-dist --no-progress
                  fi

            - name: 啟用外掛
              run: |
                  # 返回 WordPress 根目錄啟用外掛
                  cd /tmp/wordpress
                  wp plugin activate ${{ env.PLUGIN_NAME }}

            - name: 執行測試
              run: |
                  cd /tmp/wordpress/wp-content/plugins/${{ env.PLUGIN_NAME }}
                  # 執行測試
                  if [ -f "composer.json" ] && grep -q '"test"' composer.json; then
                    composer test
                  else
                    echo "沒有找到測試命令"
                  fi

            - name: 顯示錯誤日誌（如果測試失敗）
              if: failure()
              run: |
                  if [ -f /tmp/wordpress/wp-content/debug.log ]; then
                    echo "=== WordPress Debug Log ==="
                    tail -100 /tmp/wordpress/wp-content/debug.log
                  fi