name: WordPress Plugin 測試

env:
    PLUGIN_NAME: "power-webinar"
    REPO_URL: "https://github.com/j7-dev/wp-power-webinar.git"
    PHP_VERSION: "8.1"
    MYSQL_DATABASE: wordpress_test
    MYSQL_ROOT_PASSWORD: root

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
                    MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: 檢出程式碼
              uses: actions/checkout@v4

            - name: 設定 PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PHP_VERSION }}
                  extensions: mysqli, mbstring, xml, zip, gd, curl
                  tools: composer, wp-cli

            - name: 等待 MySQL 準備就緒
              run: |
                  until mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
                    echo '等待 MySQL 啟動...'
                    sleep 2
                  done

            - name: 下載並設定 WordPress
              run: |
                  # 下載 WordPress
                  wp core download --path=wordpress
                  
                  # 建立 wp-config.php
                  cd wordpress
                  wp config create \
                    --dbname=${{ env.MYSQL_DATABASE }} \
                    --dbuser=root \
                    --dbpass=${{ env.MYSQL_ROOT_PASSWORD }} \
                    --dbhost=127.0.0.1 \
                    --dbprefix=wp_ \
                    --extra-php <<PHP
                  define( 'WP_DEBUG', true );
                  define( 'WP_DEBUG_LOG', true );
                  define( 'WP_DEBUG_DISPLAY', false );
                  PHP

            - name: 初始化 WordPress
              run: |
                  cd wordpress
                  # 使用 WP-CLI 安裝 WordPress
                  wp core install \
                    --url=http://localhost \
                    --title="Test Site" \
                    --admin_user=admin \
                    --admin_password=admin \
                    --admin_email=admin@test.com \
                    --skip-email

            - name: 克隆並安裝外掛
              run: |
                  cd wordpress/wp-content/plugins
                  
                  # 克隆你的外掛 (可以直接使用 checkout 的程式碼)
                  # 如果外掛程式碼已經在 checkout 中，可以直接複製
                  cp -r $GITHUB_WORKSPACE ./${{ env.PLUGIN_NAME }}
                  
                  # 或者從其他 repo 克隆
                  # git clone ${{ env.REPO_URL }} ${{ env.PLUGIN_NAME }}
                  
                  # 返回 WordPress 根目錄啟用外掛
                  cd ../..
                  wp plugin activate ${{ env.PLUGIN_NAME }}

            - name: 安裝依賴並執行測試
              run: |
                  cd wordpress/wp-content/plugins/${{ env.PLUGIN_NAME }}
                  
                  # 安裝 Composer 依賴（如果存在）
                  if [ -f "composer.json" ]; then
                    composer install --prefer-dist --no-progress
                  fi
                  
                  # 執行測試
                  if [ -f "composer.json" ] && grep -q '"test"' composer.json; then
                    composer test
                  else
                    echo "沒有找到測試命令"
                  fi

            - name: 顯示錯誤日誌（如果測試失敗）
              if: failure()
              run: |
                  if [ -f wordpress/wp-content/debug.log ]; then
                    echo "=== WordPress Debug Log ==="
                    tail -100 wordpress/wp-content/debug.log
                  fi